osc = no

# ========== 跳过片头片尾设置 ==========
# --start=+120 # 从开始后120秒播放 || --end=-40 # 到结尾前40秒时退出
# start = +120
# --end = -100

border = no
osd-level = 1 # osd显示等级（osd-status-msg），1仅状态改变显示、3全部显示
# 显示百分比：${time-pos}/${duration}${?percent-pos:(${percent-pos}%)}'
osd-status-msg = ${time-pos}/${duration}\n🕒 ${clock}  # 显示播放时间和系统时间
osd-font-size = 10
osd-align-x = right
osd-bar = no
osd-border-size = 1
# sub-ass-override = strip # 控制字幕是否应该应用用户风格覆盖。
osd-outline-size = 0
osd-bold = yes
sub-color = '#dadee3'
sub-font-size = 36
blend-subtitles=yes
volume-max = 100
load-context-menu=yes
# ========== 色彩优化（可自行需求开启） ==========
contrast=5
saturation=3
# brightness=0
# 开启去隔行扫描-去除摩尔纹
# deinterlace=yes
# ========== 自动加载 ==========
sub-auto=fuzzy
audio-file-auto=fuzzy

# ========== 提速必关 ==========
icc-profile-auto=no
# ========== 降低同步/脚本消耗 ==========
# 禁用统计信息/调试输出
terminal=no
msg-level=all=error
# ===========
save-position-on-quit = yes
video-sync=display-resample
autofit=50

# === HDR 核心 注：新增配置字段的话请务必在此上方添加，否则配置可能无效====
# ====================================================================
# 1. 跨平台通用基础渲染设置（所有系统共用）
# ====================================================================
vo=gpu-next                             # 使用下一代渲染器，全平台完美支持 HDR 和杜比视界
target-colorspace-hint=yes              # 核心！自动检测系统 HDR 状态，开启则真 HDR 输出，关闭则完美转 SDR
tone-mapping=spline                     # 顶级的样条线色调映射算法，在 SDR 屏幕上完美转换 HDR
tone-mapping-visual-target=reproduce    # 还原导演原本的亮度和对比度意图
hwdec=auto                              # 硬件解码自动，根据系统和视频自动选择最佳解码方式
# 高画质拉伸算法
cscale=ewa_lanczos                      # 颜色无损重建
scale=spline36                          # 画面放大
dscale=mitchell                         # 4K 视频缩小至低分辨率屏幕时的最佳算法
# ====================================================================
# 2. Windows 系统专属自动化配置
# ====================================================================
[os=win32]                              # 当检测到系统为 Windows 时，自动启用以下参数
gpu-api=d3d11                           # 强力推荐 Windows 最稳健的 D3D11 接口
d3d11-output-format=rgb10_a2            # 强制点亮 10-bit 色彩通道，彻底消除色彩断层
hwdec=d3d11va-copy                      # 开启 Windows 高效硬件解码兼顾色彩滤镜
# ====================================================================
# 3. macOS 系统专属自动化配置
# ====================================================================
[os=darwin]                             # 当检测到系统为 Mac 时，自动启用以下参数
gpu-api=vulkan                          # Mac 下 gpu-next 配合 Vulkan(MoltenVK) 拥有最佳的 HDR 色彩管理
hwdec=videotoolbox-copy                 # 开启苹果专用的 VideoToolbox 硬解，省电、发热极低
# ====================================================================
# 4. Linux 系统专属自动化配置
# ====================================================================
[os=linux]                              # 当检测到系统为 Linux 时，自动启用以下参数
gpu-api=vulkan                          # Linux 下现代化渲染最完美的 Vulkan 接口
hwdec=vaapi-copy                        # 开启 Linux 通用的 VAAPI 硬件解码