# ======用户设置自动保存的配置属性======
# ======下次启动会根据用户设置加载======

# 音量
volume=yes
# 视频帧同步模式
video-sync=yes
# 自动加载icc配置文件
icc-profile-auto=yes
# 色彩调整
contrast=yes
# 亮度
brightness=yes
# 伽马
gamma=yes
# 饱和度
saturation=yes
# 色调
hue=yes
# 自动适应窗口大小
autofit=yes